[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "robotframework-soaplibrary2"
version = "1.4.3"
description = "SOAP Library for Robot Framework"
readme = "README.md"
requires-python = ">=3.7"

dependencies = [
    "robotframework",
    "zeep",
    "requests",
    "urllib3",
    "setuptools"
]

[project.optional-dependencies]

[project.urls]
Homepage = "https://github.com/MarketSquare/Robot-Framework-SOAP-Library"
